#ifndef _MX_ERROR_CODE_H
#define _MX_ERROR_CODE_H

enum file_distrib_type
{
	FILE_DIS_SUC = 0,
	FILE_DIS_CREATEINSTANCEERR = 30001,
	FILE_DIS_NOINSTANCE	   = 30002,
	FILE_DIS_CREATEDTHREADERR  = 30002,
	FILE_DIS_CREATEDIRERR,
	FILE_DIS_ACCESSSRCPATHERR,
	FILE_DIS_ACCESSDSTPATHERR,
	FILE_DIS_OPENSRCERR,
	FILE_DIS_WRITEDSTERR,

};


#endif
